### ISSUE TITLE
No message is posted after a first `/start`

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/command-start-stop#34]
After the first `/start` message, no message seems to be posted if the user tries to do `/start` again (neither "you are already assigned" or "you cannot assign yourself again" etc.). However I do see the proper logs in Cloudflare. Not sure if that was introduced by some merge.

@Keyrxng rfc

---

This is only valid for the `development` branch not the main one.

**Comment by Keyrxng** [comment]
https://github.com/ubq-testing/command-start-stop/issues/18
https://github.com/ubq-testing/command-start-stop/issues/17

I wasn't able to reproduce a non-response but it has highlighted a couple of issues so I will open a PR to address those.

1. The new string param is not diffed and responds in both scenarios `startRequiresWallet: true & false` so it appears misleading
2. Using `APP_ID` to detect the bot is not suitable as the bot has it's own `userId`, we'd need to check installs like we do now in other repos using the private key etc. So it has to be either the bot's userId or the `app_slug` (i.e it's name)

Which option would be best, user_id or name? I think name is more appropriate as this is tied to the `app_slug` which is universal across all installs and does not require using injecting `APP_PRIVATE_KEY` in order to pull installs to match userId? @0x4007 @gentlementlegen

**Comment by Keyrxng** [comment]
I'm pretty sure the current deployment is coming from `development`

**Comment by 0x4007** [comment]
usernames should be forbidden. use user id

**Comment by 0x4007** [comment]
> usernames should be forbidden. use user id, or "app id"

**Comment by gentlementlegen** [comment]
Seems to be working so far.
